---
apiVersion: v1
kind: Secret
metadata:
  name: test
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com:Khachik001/helm.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDUSXTkcmcjkSUdMFHOHGwdJ4evnevLffY1C19rZ93RGQAAAJjyH46X8h+O
    lwAAAAtzc2gtZWQyNTUxOQAAACDUSXTkcmcjkSUdMFHOHGwdJ4evnevLffY1C19rZ93RGQ
    AAAEA+Mf3LQNaLO3hmZ2inMqJFCPuuw3UJNtuDuyOPWMG/uNRJdORyZyORJR0wUc4cbB0n
    h6+d68t99jULX2tn3dEZAAAAD2FyZ29jZEB0ZXN0LmNvbQECAwQFBg==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
