apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intern-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Chart-test/
    repoURL: https://github.com/Khachik001/helm
    targetRevision: HEAD
    helm:
      values: |
        ports.container_port: 80
        ports.lb_port: 80
        host: dev-kub.am
        replicaCount: 3 
        containers:
          image: nginx
          tag: latest
            
          
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
