apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.12.1
    helm:
      values: |
        serviceAccount:
          annotations: 
            {{ toYaml .Values.keda.serviceAccount.annotations | indent 4 }}
        podSecurityContext:
          operator:
            fsGroup: 1001
            runAsGroup: 1001
            runAsUser: 1001    
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
